PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?s
WHERE {
  ?s ?p ?o .
  FILTER NOT EXISTS { ?s rdfs:label ?label }
  FILTER NOT EXISTS { ?s skos:prefLabel ?skoslabel }
  FILTER ( ?p != rdf:type )
} ORDER BY ?s
