# Use case: Event / Team / 2. Which team won the game?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>

SELECT ?teamName ?score ?opposingScore
WHERE {
    ?team rdf:type sport:Team .
    ?team sport:name ?teamName . 
    ?teamParticipation sport:participationBy ?team .
    ?teamParticipation spstat:score ?score .
    ?teamParticipation spstat:score-opposing ?opposingScore .
    FILTER ( ?score > ?opposingScore )
}
