# Use case: Event / Player / 3. How many minutes did this player play?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema/>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX schemaorg:  <https://schema.org/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>
PREFIX spsocstat: <http://cv.iptc.org/newscodes/spsocstat/>
PREFIX spplayerstatus: <http://cv.iptc.org/newscodes/spplayerstatus/>

SELECT ?playerName ?minutesPlayed
WHERE
	{ 
	?event rdf:type sport:Event .
	?event sport:participation ?playerperf .
	?playerperf sport:participationBy ?player .
	?player sport:name ?playerName . 
    ?playerperf spstat:time-played-total ?minutesPlayed .
}
ORDER BY ?playerName
