# Use case: Event / Team / 6. Who was penalised? (All fouls)

# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <https://sportschema.org/ontologies/main/>
PREFIX spsocstat: <https://sportschema.org/ontologies/soccer/>

SELECT ?teamName ?playerName ?foulsCommitted
WHERE { 
    ?event rdf:type sport:Event ;
           sport:participation ?individualParticipation ;
           sport:participation ?teamParticipation .
    ?individualParticipation rdf:type sport:IndividualParticipation ;
                             spsocstat:foulsCommited ?foulsCommitted ;
                             sport:participationBy ?player .
    ?player rdf:type sport:Athlete ;
            rdfs:label ?playerName .
    ?members rdf:type sport:IndividualMembership ;
             sport:member ?player ;
    		 sport:membershipOf ?team .
    ?team rdf:type sport:Team ;
          rdfs:label ?teamName ;
          sport:membership ?members .
    ?teamParticipation rdf:type sport:TeamParticipation ;
                       sport:participationBy ?team .
    FILTER (?foulsCommitted > "0")
    FILTER (?event = <http://example.com/Event/E2128607>)
}
ORDER BY ?teamName ?playerName
#ORDER BY ?playerName
