# Use case: Event / Player / What are this player's stats for the game?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>
PREFIX spsocstat: <http://cv.iptc.org/newscodes/spsocstat/>

SELECT ?teamName ?playerName ?stat ?statValue
WHERE { 
    ?team rdf:type sport:Team .
    ?team rdfs:label ?teamName . 
    ?team sport:membership ?members . 
    ?members sport:membershipBy ?player .
    ?player rdf:type sport:Athlete .
    ?player rdfs:label ?playerName .
    ?playerParticipcation sport:participationBy ?player .
    ?playerParticipcation rdf:type sport:IndividualParticipation .
    ?playerParticipcation ?stat ?statValue .
    FILTER (strStarts(str(?stat), "http://cv.iptc.org/newscodes/")) .
}
