# Use case: Event / Player / 3. How many minutes did this player play?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <https://sportschema.org/ontologies/main/>
PREFIX spstat: <https://sportschema.org/ontologies/corestatistics/>

SELECT ?playerName ?minutesPlayed
WHERE { 
    ?event rdf:type sport:Event .
    ?event sport:eventParticipation ?playerperf .
    ?playerperf sport:participationBy ?player .
    ?player rdfs:label ?playerName . 
    ?playerperf spstat:timePlayedTotal ?minutesPlayed .
    FILTER (?event = <http://example.com/Event/E2128609>)
}
ORDER BY ?playerName
