# Use case: Event / Team / 1. What is the starting lineup? (including position slated)
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <https://sportschema.org/ontologies/main/>
PREFIX spstat: <https://sportschema.org/ontologies/corestatistics/>
PREFIX spsocpos: <http://cv.iptc.org/newscodes/spsocpos/>

SELECT ?teamName ?playerName ?eventPosition
WHERE {
    ?event rdf:type sport:Event ;
           rdfs:label ?eventName ;
		   sport:eventParticipation ?Participation .
    ?Participation rdf:type sport:TeamParticipation ;
                   sport:participationBy ?team .
    ?team rdf:type sport:Team ;
		  rdfs:label ?teamName ;
		  sport:membership ?playerMembership .
	?playerMembership rdf:type sport:IndividualMembership ;
			sport:membershipBy ?player .
    ?tParticipation rdf:type sport:IndividualParticipation ;
    				 sport:participationBy ?player ;
                         sport:playerStatus <http://cv.iptc.org/newscodes/spplayerstatus/starter> ;
                         sport:positionEvent ?eventPosition .
    ?player rdf:type sport:Athlete ;
            rdfs:label ?playerName . 
    FILTER (?event = <http://example.com/Event/E2128610>)
}
ORDER BY ?teamName ?playerName
