# Use case: Event / Player / Did this player score a goal?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema/>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX schemaorg:  <https://schema.org/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>
PREFIX spsocstat: <http://cv.iptc.org/newscodes/spsocstat/>
PREFIX spplayerstatus: <http://cv.iptc.org/newscodes/spplayerstatus/>

SELECT ?playerName ?goals
WHERE
{
	{ 
	?event rdfs:type sport:Event .
	?event (schemaorg:awayTeam | schemaorg:homeTeam) ?team .
	?team schemaorg:athlete ?player . 
	?player schemaorg:name ?playerName . 
	}

{	
	?event sport:performance ?playerperf .
	?playerperf sport:performedBy ?player .
	?playerperf spsocstat:goals-total ?goals .
}}