# Use case: Event / Team / 1. What is the starting lineup? (including position slated)
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>
PREFIX spsocpos: <http://cv.iptc.org/newscodes/spsocpos/>

SELECT ?teamName ?playerName ?playerPos
WHERE {
    ?team rdf:type sport:Team .
    ?player rdf:type  sport:Athlete .
    ?event rdf:type  sport:Event .
    ?participation rdf:type  sport:IndividualParticipation .
    ?team sport:athlete ?player .
    ?team sport:name ?teamName .
    ?player sport:name ?playerName .
    ?player sport:position-regular ?playerPos .
    ?participation sport:participationBy ?player .
    ?participation spstat:events-started "1"
}
ORDER BY ?teamName ?playerName
