# Use case: Event / Player / 4. Did this player score a goal?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX spsocstat: <http://cv.iptc.org/newscodes/spsocstat/>

SELECT ?playerName ?goals
WHERE { 
    ?event rdf:type sport:Event .
    ?event sport:participation ?playerperf .
    ?playerperf sport:participationBy ?player .
    ?player rdfs:label ?playerName . 
    ?playerperf spsocstat:goals-total ?goals .
    FILTER ( ?goals > "0" )
}
