# Use case: Event / Team / What was the score of the game?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>

SELECT ?name ?score
WHERE { 
    ?team rdf:type sport:Team .
    ?team sport:name ?name . 
    ?teamParticipation sport:participationBy ?team .
    ?teamParticipation rdf:type sport:TeamParticipation .
    ?teamParticipation spstat:score ?score .
}
