# Use case: Event / Team / Which team won the game?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema/>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX schemaorg:  <https://schema.org/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>
PREFIX spsocstat: <http://cv.iptc.org/newscodes/spsocstat/>

SELECT ?name
WHERE
{
	?team rdfs:type sport:Team .
	?team schemaorg:name ?name . 
	?teamPartic sport:participationBy ?team .
	?teamPartic spstat:score ?score .
	?teamPartic spstat:score-opposing ?opposingScore .
	FILTER (
		?score > ?opposingScore
	)
}