# Use case: Event / Player / 4. Did this player score a goal?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <https://sportschema.org/ontologies/main/>
PREFIX spsocstat: <https://sportschema.org/ontologies/soccer/>

SELECT ?playerName ?goals
WHERE { 
    ?event rdf:type sport:Event ;
           sport:participation ?playerperf .
    ?playerperf rdf:type sport:IndividualParticipation ;
                sport:participationBy ?player ;
                spsocstat:goalsTotal ?goals .
    ?player rdf:type sport:Athlete ;
            rdfs:label ?playerName . 
    FILTER ( ?goals > "0" )
    FILTER ( ?event = <http://example.com/Event/E2128610>)
}
