# Use case: Event / Team / 5. What were the stats for each team?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>
PREFIX spsocstat: <http://cv.iptc.org/newscodes/spsocstat/>
PREFIX speventoutcome: <http://cv.iptc.org/newscodes/speventoutcome/>

SELECT ?teamName ?stat ?statValue
WHERE { 
    ?team rdf:type sport:Team ;
          rdfs:label ?teamName . 
    ?teamParticipation rdf:type sport:TeamParticipation ;
                        sport:participationBy ?team ;
                        ?stat ?statValue .
    ?event rdf:type sport:Event ;
           sport:eventParticipation ?teamParticipation .
    FILTER (strStarts(str(?stat), "http://cv.iptc.org/newscodes/")) .
    FILTER (?event = <http://example.com/Event/E755363>)
}
