# Use case: Event / Team / 6. Who was penalised? (All fouls)

# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX spsocstat: <http://cv.iptc.org/newscodes/spsocstat/>

SELECT ?teamName ?playerName ?foulsCommitted
WHERE { 
    ?individualParticipation spsocstat:fouls-commited ?foulsCommitted .
    ?individualParticipation rdf:type sport:IndividualParticipation .
    ?individualParticipation sport:participationBy ?player .
    ?player rdf:type sport:Athlete .
    ?player rdfs:label ?playerName .
    ?teams sport:membership ?members .
    ?members sport:membershipBy ?player ;
    		 sport:membershipOf ?team .
    ?team rdf:type sport:Team .
    ?team rdfs:label ?teamName . 
    FILTER (?foulsCommitted > "0")
}
ORDER BY ?teamName ?playerName
