# Use case: Event / League / 5. What time does the game begin?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 

SELECT (CONCAT(STR(HOURS(?date)),":",STR(MINUTES(?date))) as ?displayTime)
WHERE
{
    ?event rdf:type sport:Event .
    ?event sport:startDateTime ?date .
    FILTER ( ?event = <http://example.com/Event/E755363> )
}
