# Get a list of all sports covered in the entire triple store

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sport: <https://sportschema.org/ontologies/main/>

SELECT DISTINCT ?sport ?comp ?comptype ?governingBody
WHERE {
    ?comp rdf:type sport:Competition ;
    	sport:competitionType ?comptype ;
          sport:sport ?sport .
    OPTIONAL {
          ?comp sport:governingBody ?governingBody .
    }
}
