# Get a list of all sports covered in the entire triple store

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>

SELECT ?sport ?comp ?comptype ?governingBody
WHERE {
    ?comp rdf:type ?comptype ;
          sport:sport ?sport .
    OPTIONAL {
          ?comp sport:governingBody ?governingBody .
    }
}
