# Use case: get all events for a competition/eague
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema/>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX schemaorg:  <https://schema.org/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 


SELECT (CONCAT(MONTH(?date), YEAR(?date)) as ?displayDate)
       (COUNT(?event) AS ?events)
       (GROUP_CONCAT(DISTINCT ?event; SEPARATOR=", ") AS ?IDs)
WHERE
{
	?event sport:startDate ?date .
}
GROUP BY ?date
ORDER BY ?date
