# Use case: Season / League / 1. What are the current standings?
# Use case: What is the team record broken down into home and away events?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <https://sportschema.org/ontologies/main/>
PREFIX spstat: <https://sportschema.org/ontologies/corestatistics/>
PREFIX spsocstat: <https://sportschema.org/ontologies/soccer/>
PREFIX spcompetitionscope: <http://cv.iptc.org/newscodes/spcompetitionscope/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 

SELECT ?compName ?teamName ?rank
WHERE
{
    ?competition rdf:type sport:Competition ;
                 rdfs:label ?compName ;
                 sport:participation ?teamperf .
    ?teamperf sport:participationBy ?team ;
              rdf:type sport:TeamParticipation ;
              sport:rank ?rankstr .
    ?team rdfs:label ?teamName ; 
          rdf:type sport:Team .

    FILTER (?competition = <http://example.com/Competition/OLYS2020>)
    BIND (xsd:integer(?rankstr) as ?rank)
}
ORDER BY ASC(?rank)
