# filename: queries/player-01-players-in-team-B.rq
# Use case Player-01: Who are the players in a given team?

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema/>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX schemaorg:  <https://schema.org/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>
PREFIX spsocstat: <http://cv.iptc.org/newscodes/spsocstat/>

# In the sample data we don't have team rosters or lineups,
# we just have "competitor" on the Event and "performedBy"
# on Performance. Here we go via Performance.
SELECT ?teamName ?playerName
WHERE
{
	?team rdfs:type sport:Team .
	?player rdfs:type  sport:Athlete .
	?event rdfs:type sport:Event .
	?event (schemaorg:awayTeam | schemaorg:homeTeam) ?team .
	?playerPerformance rdfs:type sport:Performance .
	?playerPerformance sport:performedBy ?player .
	?teamPerformance rdfs:type sport:Performance .
	?teamPerformance sport:performedBy ?team .
	?team schemaorg:name ?teamName .
	?player schemaorg:name ?playerName .
}
ORDER BY ?teamName ?playerName