PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:   <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?class ?property
WHERE {
  ?subject rdf:type ?class .
  ?subject ?property ?object .
  FILTER NOT EXISTS { ?property rdf:type rdf:Property }
  FILTER (!REGEX ( STR(?property), "^http://cv.iptc.org/newscodes", "i" ))
  FILTER (!REGEX ( STR(?class), "^http://www.w3.org/2004/02/skos/core", "i" ))
  FILTER ( ?class != rdfs:Class )
  FILTER ( ?class != rdf:Property )
  FILTER ( ?class != owl:Ontology )
  FILTER ( ?class != owl:Class )
  FILTER ( ?property != rdf:type )
  FILTER ( ?property != rdfs:label )
} ORDER BY ?property ?class
