# Use case: Season / League / 1. What are the current standings?
# Use case: What is the team record broken down into home and away events?
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <https://sportschema.org/ontologies/main/>
PREFIX spstat: <https://sportschema.org/ontologies/corestatistics/>
PREFIX spsocstat: <https://sportschema.org/ontologies/soccer/>

SELECT ?teamName ?GP ?P ?W ?L ?D ?GF ?GA ?GD ?WHOME ?LHOME ?WAWAY
WHERE
{
    ?season rdf:type sport:Competition ;
            sport:competitionType "http://cv.iptc.org/newscodes/spct/competition"^^xsd:anyURI ;
            sport:participation ?teamParticipation . 
    ?teamParticipation rdf:type sport:TeamParticipation ;
                       sport:participationBy ?team ;
                       sport:participationSplit ?splitaway ;
                       spstat:eventsPlayed ?GP ;
                       spstat:standingPoints ?P ;
                       spstat:wins ?W ;
                       spstat:losses ?L ;
                       spstat:ties ?D ;
                       spstat:pointsScoredFor ?GF ;
                       spstat:pointsScoredAgainst ?GA ;
                       spstat:pointsDifference ?GD ;
                       sport:participationSplit ?splithome .
    ?team rdf:type sport:Team ;
          rdfs:label ?teamName .
    ?splithome rdf:type sport:ParticipationSplit ;
               sport:participationSplitType "http://cv.iptc.org/newscodes/spcompetitionscope/events-home"^^xsd:anyURI ;
               spstat:wins ?WHOME ;
               spstat:losses ?LHOME .
    ?splitaway rdf:type sport:ParticipationSplit ;
               sport:participationSplitType http://cv.iptc.org/newscodes/spcompetitionscope/events-away"^^xsd:anyURI ;
               spstat:wins ?WAWAY .
    FILTER (?season = <http://example.com/Competition/l.premierleague.com-2020>)
}
ORDER BY DESC(?P) DESC(?W) DESC(?GD)
