# Get a list of all events in a given season

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX sport: <https://sportschema.org/ontologies/main/>

SELECT ?league ?season ?event WHERE {
    ?league rdf:type sport:Competition ;
          sport:sport ?sport .
    ?season rdf:type sport:Competition ;
            sport:parent ?league .
    ?event rdf:type sport:Event ;
           sport:competition ?season .
    FILTER (?season = <http://example.com/Competition/l.premierleague.com-2020>)
}
