# Use case: Season / Team / 1. Who plays for the team? (Includes jersey number, position, etc.)
# https://github.com/iptc/sport-model/wiki/Use-Cases

PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>
PREFIX spsocstat: <http://cv.iptc.org/newscodes/spsocstat/>
PREFIX spsocposition: <http://cv.iptc.org/newscodes/spsocposition/>
PREFIX spichposition: <http://cv.iptc.org/newscodes/spichposition/>

SELECT ?teamName ?playerName ?playerPos ?dob ?uniformNumber
WHERE
{
    ?teams sport:membership ?members .
    ?members sport:membershipBy ?player ;
    		 sport:membershipOf ?team .
    ?player rdf:type  sport:Athlete .
    ?team rdf:type sport:Team ;
		  rdfs:label ?teamName .
    ?player rdfs:label ?playerName .
    OPTIONAL { ?members sport:positionRegular ?playerPos . }
    OPTIONAL { ?members sport:uniformNumber ?uniformNumber . }
    OPTIONAL { ?player sport:dateOfBirth ?dob . }
}
ORDER BY ?teamName ?playerName
