# filename: queries/T01-players-in-team.rq
# Use case Team-01: Who are the players in a given team?

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema/>
PREFIX sport: <http://www.iptc.org/ontologies/Sport/>
PREFIX schemaorg:  <https://schema.org/>
PREFIX spstat: <http://cv.iptc.org/newscodes/spstat/>
PREFIX spsocstat: <http://cv.iptc.org/newscodes/spsocstat/>

SELECT ?teamName ?playerName
WHERE
{
	?team rdfs:type sport:Team .
	?player rdfs:type  sport:Athlete .
	?team schemaorg:athlete ?player .
	?team schemaorg:name ?teamName .
	?player schemaorg:name ?playerName .
}
ORDER BY ?teamName ?playerName
