# This is a basic workflow to help you get started with Actions

name: Auto-assign to project

# Controls when the workflow will run
on:
  issues:
    types: [opened]
jobs:
  createCard:
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Sports Data
          column-name: New
